"""
`metric_plot.py` — Metrics visualization (per-class confusion-style plots)

This script reads the metrics JSON generated by `metric_compute.py` and writes a
2x2 “confusion-style” heatmap per class (built from instance-level TP/FP/FN).
It also annotates the plot title with Precision/Recall/F1 and (if available)
Boundary F1, so you can quickly compare performance across classes.

Inputs
----------------
- `--metrics_json`: Path to the JSON produced by `metric_compute.py`, typically containing:
  - `per_class.<cls>.tp / fp / fn`
  - `per_class.<cls>.precision / recall / f1`
  - `per_class.<cls>.boundary_f1` (optional; includes f1/precision/recall/tolerance_px)

Outputs
----------------
Written under `--out_dir`:
- `confusion_<cls>.png`: One PNG per class
- `confusion_plots_index.json`: Records the source JSON path and the list of generated plots

Example
----------------

    python Analysis/metric_plot.py \
      --metrics_json Analysis/src/toy_example/metrics_320_iou0.3.json \
      --out_dir      Analysis/src/toy_example/figures/confusion_plots_320_iou0.3 \
      --title_prefix ""

Dependencies
----------------
Requires `matplotlib` and `seaborn`.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

try:
    import matplotlib.pyplot as plt
    import seaborn as sns
except ModuleNotFoundError as e:  # pragma: no cover
    raise SystemExit(
        "Plotting requires matplotlib and seaborn in Python Environment. "
        "Please install: pip install matplotlib seaborn"
    ) from e


def save_per_class_confusion_matrix_plots(
    metrics_json_path: str | Path,
    out_dir: str | Path,
    title_prefix: str = "",
) -> list[str]:
    metrics_json_path = Path(metrics_json_path)
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    data = json.loads(metrics_json_path.read_text(encoding="utf-8"))
    per_class = data.get("per_class", {})

    written: list[str] = []
    for cls, v in per_class.items():
        tp = int(v.get("tp", 0))
        fp = int(v.get("fp", 0))
        fn = int(v.get("fn", 0))
        p = float(v.get("precision", 0.0))
        r = float(v.get("recall", 0.0))
        f1 = float(v.get("f1", 0.0))

        bf1 = v.get("boundary_f1") or {}
        bf1_f1 = float(bf1.get("f1", 0.0))
        bf1_p = float(bf1.get("precision", 0.0))
        bf1_r = float(bf1.get("recall", 0.0))
        bf1_tol = bf1.get("tolerance_px", None)

        cm = np.array([[tp, fp], [fn, 0]], dtype=int)

        fig = plt.figure(figsize=(4.8, 4.2))
        ax = fig.add_subplot(1, 1, 1)
        sns.heatmap(
            cm,
            annot=True,
            fmt="d",
            cmap="Blues",
            cbar=False,
            xticklabels=["Pred: organelle", "Pred: other"],
            yticklabels=["GT: organelle", "GT: other"],
            ax=ax,
        )

        t = f"{title_prefix}{cls}" if title_prefix else cls
        if bf1_tol is None:
            ax.set_title(f"{t}\nP={p:.4f}  R={r:.4f}  F1={f1:.4f}\nBF1={bf1_f1:.4f}")
        else:
            ax.set_title(
                f"{t}\nP={p:.4f}  R={r:.4f}  F1={f1:.4f}\nBF1={bf1_f1:.4f} (P={bf1_p:.4f} R={bf1_r:.4f}, tol={bf1_tol})"
            )
        fig.tight_layout()

        out_path = out_dir / f"confusion_{cls}.png"
        fig.savefig(out_path, dpi=200)
        plt.close(fig)
        written.append(str(out_path))

    index_path = out_dir / "confusion_plots_index.json"
    index_path.write_text(
        json.dumps({"source": str(metrics_json_path), "plots": written}, indent=2),
        encoding="utf-8",
    )

    return written


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--metrics_json",
        type=str,
        default="/Volumes/T7/20251204_halfCell/CLIEM_code/Analysis/src/toy_example/metrics_320_iou0.3.json",
        help="Path to metrics JSON (e.g., metrics_320_iou0.5.json)",
    )
    parser.add_argument(
        "--out_dir",
        type=str,
        default="/Volumes/T7/20251204_halfCell/CLIEM_code/Analysis/src/toy_example/figures/confusion_plots_320_iou0.3",
        help="Directory to write confusion matrix PNGs",
    )
    parser.add_argument("--title_prefix", type=str, default="")

    args = parser.parse_args()

    written = save_per_class_confusion_matrix_plots(
        metrics_json_path=args.metrics_json,
        out_dir=args.out_dir,
        title_prefix=args.title_prefix,
    )

    print("wrote plots:")
    for p in written:
        print(p)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
